#trigger:
#- main  # Define the branch to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'  # Use an appropriate agent based on your requirements

steps:
- script: |
    docker build -t my-node-app:$(Build.BuildId) .   # Build the Docker image
    docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)  # Log in to your Docker registry
    docker tag my-node-app:$(Build.BuildId) myregistry.azurecr.io/my-node-app:$(Build.BuildId)  # Tag the image for your registry
    docker push myregistry.azurecr.io/my-node-app:$(Build.BuildId)  # Push the image to the registry
  displayName: 'Build and Push Docker Image'
  env:
    DOCKER_USERNAME: $(DOCKER_USERNAME)  # Define these variables in your Azure DevOps pipeline settings
    DOCKER_PASSWORD: $(DOCKER_PASSWORD)
