# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- nomain

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image and push
      inputs:
        # command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile2'
        containerRegistry: 'itservicesaj'
        repository: 'itservicesaj/ibm-node-hello'
        command: 'buildAndPush'
        #Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
